//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class BANKS
    {
        public BANKS()
        {
            this.CREDITS = new HashSet<CREDITS>();
        }
    
        [DataMember]
        public int BANK_ID { get; set; }
        [DataMember]
        public string BANK_NAME { get; set; }
        [DataMember]
        public Nullable<int> LOCATION_ID { get; set; }

        [DataMember]
        public virtual LOCATIONS LOCATIONS { get; set; }
        [JsonIgnore]
        public virtual ICollection<CREDITS> CREDITS { get; set; }
    }
}
