//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class CREDITS
    {
        public CREDITS()
        {
            this.FIZLICO = new HashSet<FIZLICO>();
            this.URLICO = new HashSet<URLICO>();
        }
    
        [DataMember]
        public int CREDIT_ID { get; set; }
        [DataMember]
        public Nullable<int> BANK_ID { get; set; }
        [DataMember]
        public Nullable<int> CREDIT_SUM { get; set; }
        [DataMember]
        public Nullable<short> SROK_PERYEAR { get; set; }
        [DataMember]
        public Nullable<System.DateTime> DATE_ISSUE { get; set; }
        [DataMember]
        public Nullable<short> PERCENT_PERYEAR { get; set; }
        [DataMember]
        public Nullable<short> FINE_PERYEAR { get; set; }
        [DataMember]
        public Nullable<short> CSTATUS_ID { get; set; }

        [DataMember]
        public virtual BANKS BANKS { get; set; }
        [DataMember]
        public virtual CREDIT_STATUS CREDIT_STATUS { get; set; }
        [JsonIgnore]
        public virtual ICollection<FIZLICO> FIZLICO { get; set; }
        [JsonIgnore]
        public virtual ICollection<URLICO> URLICO { get; set; }
    }
}
