//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class FIZLICO
    {
        [DataMember]
        public int FIZLICO_ID { get; set; }
        [DataMember]
        public string FULL_NAME { get; set; }
        [DataMember]
        public string PHONE_NUMBER { get; set; }
        [DataMember]
        public string IDCARD_ANN { get; set; }
        [DataMember]
        public Nullable<System.DateTime> DATE_BIRTH { get; set; }
        [DataMember]
        public Nullable<short> GENDER_ID { get; set; }
        [DataMember]
        public Nullable<short> MSTATUS_ID { get; set; }
        [DataMember]
        public Nullable<short> NATIONALITY_ID { get; set; }
        [DataMember]
        public Nullable<int> CREDIT_ID { get; set; }
        [DataMember]
        public Nullable<int> LOCATION_ID { get; set; }

        [DataMember]
        public virtual CREDITS CREDITS { get; set; }
        [DataMember]
        public virtual GENDER GENDER { get; set; }
        [DataMember]
        public virtual LOCATIONS LOCATIONS { get; set; }
        [DataMember]
        public virtual MARITAL_STATUS MARITAL_STATUS { get; set; }
        [DataMember]
        public virtual NATIONALITIES NATIONALITIES { get; set; }
    }
}
