//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class GENDER
    {
        public GENDER()
        {
            this.FIZLICO = new HashSet<FIZLICO>();
        }

        [DataMember]
        public short GENDER_ID { get; set; }
        [DataMember]
        public string GENDER_NAME { get; set; }

        //[JsonIgnore]
        public virtual ICollection<FIZLICO> FIZLICO { get; set; }
    }
}
