//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BANKS> BANKS { get; set; }
        public DbSet<CREDIT_STATUS> CREDIT_STATUS { get; set; }
        public DbSet<CREDITS> CREDITS { get; set; }
        public DbSet<FIZLICO> FIZLICO { get; set; }
        public DbSet<GENDER> GENDER { get; set; }
        public DbSet<LOCATIONS> LOCATIONS { get; set; }
        public DbSet<MARITAL_STATUS> MARITAL_STATUS { get; set; }
        public DbSet<NATIONALITIES> NATIONALITIES { get; set; }
        public DbSet<URLICO> URLICO { get; set; }
    }
}
