//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class LOCATIONS
    {
        public LOCATIONS()
        {
            this.BANKS = new HashSet<BANKS>();
            this.FIZLICO = new HashSet<FIZLICO>();
            this.URLICO = new HashSet<URLICO>();
        }
    
        [DataMember]
        public int LOCATION_ID { get; set; }
        [DataMember]
        public string STREET_ADDRESS { get; set; }
        [DataMember]
        public string POSTAL_CODE { get; set; }
        [DataMember]
        public string CITY_PROVINCE { get; set; }

        [JsonIgnore]
        public virtual ICollection<BANKS> BANKS { get; set; }
        [JsonIgnore]
        public virtual ICollection<FIZLICO> FIZLICO { get; set; }
        [JsonIgnore]
        public virtual ICollection<URLICO> URLICO { get; set; }
    }
}
