//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class URLICO
    {
        [DataMember]
        public int URLICO_ID { get; set; }
        [DataMember]
        public string URLICO_NAME { get; set; }
        [DataMember]
        public string URLICO_PHONE { get; set; }
        [DataMember]
        public Nullable<int> CREDIT_ID { get; set; }
        [DataMember]
        public Nullable<int> LOCATION_ID { get; set; }

        [DataMember]
        public virtual CREDITS CREDITS { get; set; }
        [DataMember]
        public virtual LOCATIONS LOCATIONS { get; set; }
    }
}
